/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SCascader: typeof import('./src/components/vs-search/components/s-cascader/s-cascader.vue')['default']
    SDate: typeof import('./src/components/vs-search/components/s-date/s-date.vue')['default']
    SDatetime: typeof import('./src/components/vs-search/components/s-datetime/s-datetime.vue')['default']
    SInput: typeof import('./src/components/vs-search/components/s-input/s-input.vue')['default']
    SSelect: typeof import('./src/components/vs-search/components/s-select/s-select.vue')['default']
    VsColorPicker: typeof import('./src/components/vs-color-picker/vs-color-picker.vue')['default']
    VsDividerTitle: typeof import('./src/components/vs-divider-title/vs-divider-title.vue')['default']
    VsLabel: typeof import('./src/components/vs-label/vs-label.vue')['default']
    VsSearch: typeof import('./src/components/vs-search/vs-search.vue')['default']
    VsTreeSelect: typeof import('./src/components/vs-tree-select/vs-tree-select.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
