/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    MyColorPicker: (typeof import('./src/components/vs-color-picker/my-color-picker.vue'))['default']
    MyDividerTitle: (typeof import('./src/components/vs-divider-title/my-divider-title.vue'))['default']
    MyLabel: (typeof import('./src/components/vs-label/vs-label.vue'))['default']
    MySearch: (typeof import('./src/components/vs-search/vs-search.vue'))['default']
    MyTreeSelect: (typeof import('./src/components/vs-tree-select/vs-tree-select.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SInput: typeof import('./src/components/vs-search/components/s-input/s-input.vue')['default']
    VsColorPicker: typeof import('./src/components/vs-color-picker/vs-color-picker.vue')['default']
    VsDividerTitle: typeof import('./src/components/vs-divider-title/vs-divider-title.vue')['default']
    VsLabel: typeof import('./src/components/vs-label/vs-label.vue')['default']
    VsSearch: typeof import('./src/components/vs-search/vs-search.vue')['default']
    VsTreeSelect: typeof import('./src/components/vs-tree-select/vs-tree-select.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
